-- 천재지변으로 인해 일부 데이터가 유실되었습니다.
-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회하는 SQL문을 작성해주세요.
SELECT A.ANIMAL_ID, A.NAME
FROM(
    SELECT AO.ANIMAL_ID, AO.NAME, AI.INTAKE_CONDITION
    FROM ANIMAL_INS AS AI LEFT OUTER JOIN ANIMAL_OUTS AS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
    UNION
    SELECT AO.ANIMAL_ID, AO.NAME, AI.INTAKE_CONDITION
    FROM ANIMAL_INS AS AI RIGHT OUTER JOIN ANIMAL_OUTS AS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
) AS A
WHERE A.INTAKE_CONDITION IS NULL
ORDER BY A.ANIMAL_ID;




-- 관리자의 실수로 일부 동물의 입양일이 잘못 입력되었습니다. 
-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 
-- 이때 결과는 보호 시작일이 빠른 순으로 조회해야합니다.
SELECT A.ANIMAL_ID, A.NAME
FROM(
    SELECT AI.ANIMAL_ID, AI.NAME, AI.DATETIME AS "AID", AO.DATETIME AS "AOD"
    FROM ANIMAL_INS AS AI JOIN ANIMAL_OUTS AS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
) AS A
WHERE A.AID > A.AOD
ORDER BY A. AID;
